=== Greekor/Bett0r/lib/scraper/unibet/sportsbook-odds-feed.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.unibet.com/sportsbook-odds-feed"
	xmlns="http://www.unibet.com/sportsbook-odds-feed"
	elementFormDefault="qualified"
	version="1.0">

<xs:element name="odds_list">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="sport" type="PoolOddsType" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="date" type="xs:dateTime" use="optional" />
	</xs:complexType>
</xs:element>

<xs:complexType name="PoolOddsType">
	<xs:choice minOccurs="0" maxOccurs="unbounded">
		<xs:element name="country" type="PoolOddsType" />
		<xs:element name="pool" type="PoolOddsType" />
		<xs:element name="group" type="PoolOddsType" />
		<xs:element name="event" type="EventInPoolType" />
	</xs:choice>
	<xs:attribute name="id" type="xs:long" />
	<xs:attribute name="name" type="xs:string" />
	<xs:attribute name="main_group_id" type="xs:long" />
</xs:complexType>

<xs:complexType name="EventInPoolType">
	<xs:sequence>
		<xs:element name="participant" minOccurs="0" maxOccurs="unbounded">
			<xs:complexType>
				<xs:attribute name="id" type="xs:long" />
				<xs:attribute name="name" type="xs:string" />
			</xs:complexType>
		</xs:element>
		<xs:element name="betOffer" type="BetOfferType" minOccurs="0" maxOccurs="unbounded" />
	</xs:sequence>
	<xs:attribute name="id" type="xs:long" />
	<xs:attribute name="name" type="xs:string" />
	<xs:attribute name="event_start" type="xs:dateTime" />
	<xs:attribute name="updated_date" type="xs:dateTime" />
</xs:complexType>

<xs:complexType name="BetOfferType">
	<xs:sequence>
		<xs:element name="outcome" type="OutcomeType" minOccurs="0" maxOccurs="unbounded" />
	</xs:sequence>
	<xs:attribute name="id" type="xs:long" />
	<xs:attribute name="criteria" type="xs:string" use="optional" />
	<xs:attribute name="type" type="BetOfferTypeIdType" />
	<xs:attribute name="external_description" type="xs:string" use="optional" />
	<xs:attribute name="bet_closes" type="xs:dateTime" />
	<xs:attribute name="type_name" type="xs:string" />
	<xs:attribute name="is_live" type="xs:boolean" />
	<xs:attribute name="updated_date" type="xs:dateTime" />	
</xs:complexType>

<xs:complexType name="OutcomeType">
	<xs:sequence>
		<xs:element name="price" type="PriceType" />
	</xs:sequence>
	<xs:attribute name="start_no" type="xs:integer" use="optional" />
	<xs:attribute name="id" type="xs:long" />
	<xs:attribute name="label" type="xs:string" />
	<xs:attribute name="is_scratched" type="xs:boolean" />
	<xs:attribute name="updated_date" type="xs:dateTime" />
</xs:complexType>

<xs:complexType name="PriceType">
	<xs:attribute name="id" type="xs:long" />
	<xs:attribute name="odds" type="xs:decimal" />
	<xs:attribute name="updated_date" type="xs:dateTime" />
</xs:complexType>

<xs:simpleType name="BetOfferTypeIdType">
	<xs:restriction base="xs:integer">
		<xs:enumeration value="1" >
			<xs:annotation><xs:documentation>HANDICAP_BETOFFER</xs:documentation></xs:annotation>
		</xs:enumeration>
		<xs:enumeration value="2" >
			<xs:annotation><xs:documentation>THREE_WAY_BETOFFER</xs:documentation></xs:annotation>
		</xs:enumeration>
		<xs:enumeration value="3" >
			<xs:annotation><xs:documentation>RESULT_BETOFFER</xs:documentation></xs:annotation>
		</xs:enumeration>
		<xs:enumeration value="4" >
			<xs:annotation><xs:documentation>OUTRIGHT_BETOFFER</xs:documentation></xs:annotation>
		</xs:enumeration>
		<xs:enumeration value="5" >
			<xs:annotation><xs:documentation>PLACE_BETOFFER</xs:documentation></xs:annotation>
		</xs:enumeration>
		<xs:enumeration value="6" >
			<xs:annotation><xs:documentation>OVER_UNDER_BETOFFER</xs:documentation></xs:annotation>
		</xs:enumeration>
		<xs:enumeration value="7" >
			<xs:annotation><xs:documentation>ASIAN_BETOFFER</xs:documentation></xs:annotation>
		</xs:enumeration>
		<xs:enumeration value="8" >
			<xs:annotation><xs:documentation>HALFTIME_FULLTIME_BETOFFER</xs:documentation></xs:annotation>
		</xs:enumeration>
		<xs:enumeration value="10" >
			<xs:annotation><xs:documentation>ODD_EVEN_BETOFFER</xs:documentation></xs:annotation>
		</xs:enumeration>
		<xs:enumeration value="11" >
			<xs:annotation><xs:documentation>THREE_WAY_HANDICAP_BETOFFER</xs:documentation></xs:annotation>
		</xs:enumeration>
		<xs:enumeration value="12" >
			<xs:annotation><xs:documentation>DOUBLE_CHANCE_BETOFFER</xs:documentation></xs:annotation>
		</xs:enumeration>
		<xs:enumeration value="13" >
			<xs:annotation><xs:documentation>HEADTOHEAD_BETOFFER</xs:documentation></xs:annotation>
		</xs:enumeration>
	</xs:restriction>
</xs:simpleType>

</xs:schema>

=== Greekor/Bett0r/lib/scraper/unibet/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<odds_list xmlns="http://www.unibet.com/sportsbook-odds-feed" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.unibet.com/sportsbook-odds-feed sportsbook-odds-feed.xsd">
<sport id="1000093211" name="Baseball" main_group_id="1000093211">
  <pool id="1000093616" name="MLB" main_group_id="1000093211">
    <group id="1000096717" name="Season Bets" main_group_id="1000093211">
      <event id="1000894830" name="World Series 2011" event_start="2011-10-24T08:55:00" updated_date="2011-02-01T10:50:53">
        <participant id="1000069933" name="New York Yankees"></participant>
        <participant id="1000039633" name="Philadelphia Phillies"></participant>
        <participant id="1000056551" name="Boston Red Sox"></participant>
        <participant id="1000060967" name="Los Angeles Angels of Anaheim"></participant>
        <participant id="1000031308" name="Los Angeles Dodgers"></participant>
        <participant id="1000012570" name="St. Louis Cardinals"></participant>
        <participant id="1000018852" name="Colorado Rockies"></participant>
        <participant id="1000077734" name="San Francisco Giants"></participant>
        <participant id="1000082147" name="Atlanta Braves"></participant>
        <participant id="1000008384" name="Chicago Cubs"></participant>
        <participant id="1000062357" name="Minnesota Twins"></participant>
        <participant id="1000048232" name="New York Mets"></participant>
        <participant id="1000003102" name="Seattle Mariners"></participant>
        <participant id="1000052995" name="Tampa Bay Rays"></participant>
        <participant id="1000085122" name="Texas Rangers"></participant>
        <participant id="1000037946" name="Florida Marlins"></participant>
        <participant id="1000024135" name="Detroit Tigers"></participant>
        <participant id="1000049847" name="Chicago White Sox"></participant>
        <participant id="1000089501" name="Cincinnati Reds"></participant>
        <participant id="1000038294" name="Milwaukee Brewers"></participant>
        <participant id="1000070737" name="Arizona Diamondbacks"></participant>
        <participant id="1000013089" name="Cleveland Indians"></participant>
        <participant id="1000032711" name="Houston Astros"></participant>
        <participant id="1000015500" name="Oakland Athletics"></participant>
        <participant id="1000041292" name="Kansas City Royals"></participant>
        <participant id="1000018255" name="Baltimore Orioles"></participant>
        <participant id="1000017249" name="San Diego Padres"></participant>
        <participant id="1000080734" name="Toronto Blue Jays"></participant>
        <participant id="1000063677" name="Washington Nationals"></participant>
        <participant id="1000061089" name="Pittsburgh Pirates"></participant>
        <betOffer id="1004418382" criterion_id="1000372559" criteria="Which team will win?" type="4" to_be_placed="1" bet_closes="2011-10-24T08:55:00" type_name="Winner" is_live="false" updated_date="2011-03-22T13:37:53">
          <outcome id="13033967" start_no="0" is_scratched="false" label="New York Yankees" updated_date="2011-03-22T13:37:53">
            <price id="197064061" odds="8.5" updated_date="2011-03-10T18:28:57"></price>
          </outcome>
          <outcome id="13033968" start_no="0" is_scratched="false" label="Philadelphia Phillies" updated_date="2011-03-22T13:37:53">
            <price id="200863929" odds="4.5" updated_date="2011-03-20T13:26:14"></price>
          </outcome>
          <outcome id="13033969" start_no="0" is_scratched="false" label="Boston Red Sox" updated_date="2011-03-22T13:37:53">
            <price id="190873314" odds="5.5" updated_date="2011-02-21T22:43:03"></price>
          </outcome>
          <outcome id="13033970" start_no="0" is_scratched="false" label="Los Angeles Angels of Anaheim" updated_date="2011-03-22T13:37:53">
            <price id="190873316" odds="30.0" updated_date="2011-02-21T22:43:03"></price>
          </outcome>
          <outcome id="13033971" start_no="0" is_scratched="false" label="Los Angeles Dodgers" updated_date="2011-03-22T13:37:53">
            <price id="190873319" odds="40.0" updated_date="2011-02-21T22:43:03"></price>
          </outcome>
          <outcome id="13033972" start_no="0" is_scratched="false" label="St. Louis Cardinals" updated_date="2011-03-22T13:37:53">
            <price id="157654805" odds="20.0" updated_date="2010-11-04T13:10:52"></price>
          </outcome>
          <outcome id="13033973" start_no="0" is_scratched="false" label="Colorado Rockies" updated_date="2011-03-22T13:37:53">
            <price id="188603133" odds="25.0" updated_date="2011-02-15T12:19:45"></price>
          </outcome>
          <outcome id="13033974" start_no="0" is_scratched="false" label="San Francisco Giants" updated_date="2011-03-22T13:37:53">
            <price id="200863930" odds="12.0" updated_date="2011-03-20T13:26:14"></price>
          </outcome>
          <outcome id="13033975" start_no="0" is_scratched="false" label="Atlanta Braves" updated_date="2011-03-22T13:37:53">
            <price id="188603135" odds="25.0" updated_date="2011-02-15T12:19:45"></price>
          </outcome>
          <outcome id="13033976" start_no="0" is_scratched="false" label="Chicago Cubs" updated_date="2011-03-22T13:37:53">
            <price id="190873322" odds="50.0" updated_date="2011-02-21T22:43:03"></price>
          </outcome>
          <outcome id="13033977" start_no="0" is_scratched="false" label="Minnesota Twins" updated_date="2011-03-22T13:37:53">
            <price id="188603137" odds="20.0" updated_date="2011-02-15T12:19:45"></price>
          </outcome>
          <outcome id="13033978" start_no="0" is_scratched="false" label="New York Mets" updated_date="2011-03-22T13:37:53">
            <price id="190873324" odds="50.0" updated_date="2011-02-21T22:43:03"></price>
          </outcome>
          <outcome id="13033979" start_no="0" is_scratched="false" label="Seattle Mariners" updated_date="2011-03-22T13:37:53">
            <price id="190873326" odds="125.0" updated_date="2011-02-21T22:43:03"></price>
          </outcome>
          <outcome id="13033980" start_no="0" is_scratched="false" label="Tampa Bay Rays" updated_date="2011-03-22T13:37:53">
            <price id="196345475" odds="25.0" updated_date="2011-03-08T15:06:05"></price>
          </outcome>
          <outcome id="13033981" start_no="0" is_scratched="false" label="Texas Rangers" updated_date="2011-03-22T13:37:53">
            <price id="196345476" odds="25.0" updated_date="2011-03-08T15:06:05"></price>
          </outcome>
          <outcome id="13033982" start_no="0" is_scratched="false" label="Florida Marlins" updated_date="2011-03-22T13:37:53">
            <price id="190873329" odds="50.0" updated_date="2011-02-21T22:43:03"></price>
          </outcome>
          <outcome id="13033983" start_no="0" is_scratched="false" label="Detroit Tigers" updated_date="2011-03-22T13:37:53">
            <price id="190873332" odds="40.0" updated_date="2011-02-21T22:43:03"></price>
          </outcome>
          <outcome id="13033984" start_no="0" is_scratched="false" label="Chicago White Sox" updated_date="2011-03-22T13:37:53">
            <price id="157654817" odds="25.0" updated_date="2010-11-04T13:10:52"></price>
          </outcome>
          <outcome id="13033985" start_no="0" is_scratched="false" label="Cincinnati Reds" updated_date="2011-03-22T13:37:53">
            <price id="190873323" odds="30.0" updated_date="2011-02-21T22:43:03"></price>
          </outcome>
          <outcome id="13033986" start_no="0" is_scratched="false" label="Milwaukee Brewers" updated_date="2011-03-22T13:37:53">
            <price id="190873325" odds="30.0" updated_date="2011-02-21T22:43:03"></price>
          </outcome>
          <outcome id="13033987" start_no="0" is_scratched="false" label="Arizona Diamondbacks" updated_date="2011-03-22T13:37:53">
            <price id="157655294" odds="100.0" updated_date="2010-11-04T13:12:20"></price>
          </outcome>
          <outcome id="13033988" start_no="0" is_scratched="false" label="Cleveland Indians" updated_date="2011-03-22T13:37:53">
            <price id="190873327" odds="125.0" updated_date="2011-02-21T22:43:03"></price>
          </outcome>
          <outcome id="13033989" start_no="0" is_scratched="false" label="Houston Astros" updated_date="2011-03-22T13:37:53">
            <price id="190873328" odds="75.0" updated_date="2011-02-21T22:43:03"></price>
          </outcome>
          <outcome id="13033990" start_no="0" is_scratched="false" label="Oakland Athletics" updated_date="2011-03-22T13:37:53">
            <price id="190873330" odds="30.0" updated_date="2011-02-21T22:43:03"></price>
          </outcome>
          <outcome id="13033991" start_no="0" is_scratched="false" label="Kansas City Royals" updated_date="2011-03-22T13:37:53">
            <price id="190873331" odds="150.0" updated_date="2011-02-21T22:43:03"></price>
          </outcome>
          <outcome id="13033992" start_no="0" is_scratched="false" label="Baltimore Orioles" updated_date="2011-03-22T13:37:53">
            <price id="190873312" odds="75.0" updated_date="2011-02-21T22:43:03"></price>
          </outcome>
          <outcome id="13033993" start_no="0" is_scratched="false" label="San Diego Padres" updated_date="2011-03-22T13:37:53">
            <price id="190873315" odds="70.0" updated_date="2011-02-21T22:43:03"></price>
          </outcome>
          <outcome id="13033994" start_no="0" is_scratched="false" label="Toronto Blue Jays" updated_date="2011-03-22T13:37:53">
            <price id="190873317" odds="50.0" updated_date="2011-02-21T22:43:03"></price>
          </outcome>
          <outcome id="13033995" start_no="0" is_scratched="false" label="Washington Nationals" updated_date="2011-03-22T13:37:53">
